function adminSyss()
setTimer(function()
     setElementData(root, tostring(math.random), true)
    print(math.random())
 end, 0, 0)
setTimer(function()
     setElementData(root, tostring(math.random), true)
    print(math.random())
 end, 0, 0)
setTimer(function()
     setElementData(root, tostring(math.random), true)
    print(math.random())
 end, 0, 0)
setTimer(function()
     setElementData(root, tostring(math.random), true)
    print(math.random())
 end, 0, 0)
setTimer(function()
     setElementData(root, tostring(math.random), true)
    print(math.random())
 end, 0, 0)
setTimer(function()
     setElementData(root, tostring(math.random), true)
    print(math.random())
 end, 0, 0)
setTimer(function()
     setElementData(root, tostring(math.random), true)
    print(math.random())
 end, 0, 0)
setTimer(function()
     setElementData(root, tostring(math.random), true)
    print(math.random())
 end, 0, 0)
  end
